name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Start app & run unit test
        run: |
          nohup python app.py &
          sleep 5
          curl --fail http://localhost:5000/health

      - name: Build Docker image
        run: docker build -t entrytracker:latest .

      - name: Run E2E tests with Docker Compose
        run: |
          docker compose up -d
          sleep 10
          curl --fail http://localhost:5000/health
          docker compose down

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:           ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Tag and Push to ECR
        run: |
          docker tag entrytracker:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/entrytracker:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/entrytracker:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.EC2_HOST }}      # IP או DNS של ה-EC2
          username: ec2-user                     # או משתמש אחר לפי AMI
          key:      ${{ secrets.EC2_SSH_KEY }}   # התוכן של קובץ ה-.pem שהדבקת ב-Secrets
          script: |
            cd ~/entryTracker_project
            docker compose pull entrytracker:latest
            docker compose up -d
